# Generated by Django 3.1.2 on 2020-10-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20201021_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='dimension',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
